#ifndef CONFIG_TMPBEING_H
#define CONFIG_TMPBEING_H

#undef DEBOUNCE
#define DEBOUNCE 45

#undef MOUSEKEY_TIME_TO_MAX
#undef MOUSEKEY_MAX_SPEED

#define MOUSEKEY_TIME_TO_MAX 15
#define MOUSEKEY_MAX_SPEED 6

#undef TAPPING_TERM
#define TAPPING_TERM 250

#undef TAPPING_TOGGLE
#define TAPPING_TOGGLE 5

#define ONESHOT_TAP_TOGGLE 2
#define ONESHOT_TIMEOUT 3000

#undef LEADER_TIMEOUT
#define LEADER_TIMEOUT 1000

#undef RGBLIGHT_ANIMATIONS

#define RGBLIGHT_COLOR_LAYER_0 RGB_MAGENTA
#define RGBLIGHT_COLOR_LAYER_1 RGB_SPRINGGREEN
#define RGBLIGHT_COLOR_LAYER_2 RGB_GOLD
#define RGBLIGHT_COLOR_LAYER_3 RGB_RED
#define RGBLIGHT_COLOR_LAYER_4 RGB_AZURE
#define RGBLIGHT_COLOR_LAYER_5 RGB_ORANGE
#define RGBLIGHT_COLOR_LAYER_6 RGB_CORAL

#endif // CONFIG_TMPBEING_H
