#ifndef CONFIG_TMPBEING_H
#define CONFIG_TMPBEING_H

#include QMK_KEYBOARD_CONFIG_H

#undef MOUSEKEY_TIME_TO_MAX
#undef MOUSEKEY_MAX_SPEED

#define MOUSEKEY_TIME_TO_MAX 10
#define MOUSEKEY_MAX_SPEED 4

#undef TAPPING_TOGGLE
#define TAPPING_TOGGLE 2

#define ONESHOT_TAP_TOGGLE 2
#define ONESHOT_TIMEOUT 3000

#undef LEADER_TIMEOUT
#define LEADER_TIMEOUT 1000

#endif // CONFIG_TMPBEING_H
